version: "3.9"

services:
  db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stoopid1
      POSTGRES_DB: memorygame
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./apps/backend
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://postgres:stoopid1@db:5432/memorygame"
    depends_on:
      - db
    ports:
      - "4000:4000"

volumes:
  pgdata: